version: "3.8"

services:
  airflow:
    image: apache/airflow:2.10.2-python3.11
    container_name: airflow-minimal
    restart: always
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create
                 --username admin
                 --password admin
                 --firstname Admin
                 --lastname User
                 --role Admin
                 --email admin@example.com || echo 'User may already exist' &&
               airflow scheduler & airflow webserver"
